<?php
/**
 * Mageplace Backup
 *
 * @category   Mageplace
 * @package    Mageplace_Backup
 * @copyright  Copyright (c) 2014 Mageplace. (http://www.mageplace.com)
 * @license    http://www.mageplace.com/disclaimer.html
 */

/** @var Mageplace_Backup_Block_Adminhtml_Backup_Js_Finish $this */
$_finish = $this->getFinishObjectData();
?>
<script>
    MP.Backup.Finish = Class.create();
    MP.Backup.Finish.prototype = {
        <?php foreach($_finish as $key => $value) : ?>
        <?php $value = Zend_Json::encode($value); $_finish[$key] = $value; ?>
        '<?php echo $key; ?>': <?php echo $value; ?>,
        <?php endforeach; ?>

        initialize: function (obj) {
            <?php foreach($_finish as $key => $value) : ?>
            this['<?php echo $key; ?>'] = <?php echo $value; ?>;
            <?php endforeach; ?>

            if (Object.isUndefined(obj)) {
                return;
            }

            for (var prop in obj) {
                this[prop] = obj[prop];
            }
        },

        <?php foreach($_finish as $key => $value) : ?>

        get<?php echo $methodName = $this->getFinishObject()->getMethodName($key); ?>: function () {
            return this['<?php echo $key; ?>'];
        },

        set<?php echo $methodName; ?>: function (value) {
            this['<?php echo $key; ?>'] = value;
            return this;
        },
        <?php endforeach; ?>

        isFinish: function () {
            return this.getFinish() == 1;
        },

        isError: function () {
            return Object.isString(this.getError()) && this.getError() != '';
        }
    };
</script>